/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package threadrelay;

/**
 *
 * @author ARCALENI.DANIELE2
 */
public class GraficaStaffetta extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GraficaStaffetta.class.getName());
    Corridore c1;
    Corridore c2;
    Corridore c3;
    Corridore c4;
    Thread t1;
    Thread t2;
    Thread t3;
    Thread t4;
    /**
     * Creates new form GraficaStaffetta
     */
    public GraficaStaffetta() {
        initComponents();
        
        Riprendi.setEnabled(false);
        
        c1 = new Corridore(lblPrimoThread, PrimaProgressBar, null);
        c2 = new Corridore(lblSecondoThread, SecondaProgressBar, c1);
        c3 = new Corridore(lblTerzoThread, TerzaProgressBar, c2);
        c4 = new Corridore(lblQuartoThread, QuartaProgressBar, c3);
        
        t1 = new Thread(c1);
        t2 = new Thread(c2);
        t3 = new Thread(c3);
        t4 = new Thread(c4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PrimaProgressBar = new javax.swing.JProgressBar();
        SecondaProgressBar = new javax.swing.JProgressBar();
        TerzaProgressBar = new javax.swing.JProgressBar();
        QuartaProgressBar = new javax.swing.JProgressBar();
        lblPrimoThread = new javax.swing.JLabel();
        lblSecondoThread = new javax.swing.JLabel();
        lblTerzoThread = new javax.swing.JLabel();
        lblQuartoThread = new javax.swing.JLabel();
        BottoneAvvia = new javax.swing.JButton();
        Pausa = new javax.swing.JButton();
        Restart = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Riprendi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(PrimaProgressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 79, 159, 14));
        getContentPane().add(SecondaProgressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 140, 159, 14));
        getContentPane().add(TerzaProgressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 201, 159, 14));
        getContentPane().add(QuartaProgressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 267, 159, 14));

        lblPrimoThread.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblPrimoThread.setText("0");
        getContentPane().add(lblPrimoThread, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 79, 50, 16));

        lblSecondoThread.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblSecondoThread.setText("0");
        getContentPane().add(lblSecondoThread, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 134, 50, -1));

        lblTerzoThread.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblTerzoThread.setText("0");
        getContentPane().add(lblTerzoThread, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 195, 50, -1));

        lblQuartoThread.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblQuartoThread.setText("0");
        getContentPane().add(lblQuartoThread, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 261, 50, -1));

        BottoneAvvia.setText("Avvia");
        BottoneAvvia.addActionListener(this::BottoneAvviaActionPerformed);
        getContentPane().add(BottoneAvvia, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, -1, -1));

        Pausa.setText("Pausa");
        Pausa.addActionListener(this::PausaActionPerformed);
        getContentPane().add(Pausa, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 80, -1));

        Restart.setText("Restart");
        Restart.addActionListener(this::RestartActionPerformed);
        getContentPane().add(Restart, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, -1, -1));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Staffetta con i Thread");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 6, -1, -1));

        Riprendi.setText("Riprendi");
        Riprendi.addActionListener(this::RiprendiActionPerformed);
        getContentPane().add(Riprendi, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 83, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BottoneAvviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BottoneAvviaActionPerformed
        t1 = new Thread(c1);
        t2 = new Thread(c2);
        t3 = new Thread(c3);
        t4 = new Thread(c4);
        
        t1.start();
        t2.start();
        t3.start();
        t4.start();
        
        BottoneAvvia.setEnabled(false);
    }//GEN-LAST:event_BottoneAvviaActionPerformed

    private void PausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PausaActionPerformed
        c1.pausa();
        c2.pausa();
        c3.pausa();
        c4.pausa();
        
        Riprendi.setEnabled(true);
    }//GEN-LAST:event_PausaActionPerformed

    private void RiprendiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RiprendiActionPerformed
        Riprendi.setEnabled(false);
        
        c1.riprendi();
        c2.riprendi();
        c3.riprendi();
        c4.riprendi();
    }//GEN-LAST:event_RiprendiActionPerformed

    private void RestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestartActionPerformed
        BottoneAvvia.setEnabled(true);
        
        c1.fermo();
        c2.fermo();
        c3.fermo();
        c4.fermo();
        
        c1.reset();
        c2.reset();
        c3.reset();
        c4.reset();
        
        c1 = new Corridore(lblPrimoThread, PrimaProgressBar, null);
        c2 = new Corridore(lblSecondoThread, SecondaProgressBar, c1);
        c3 = new Corridore(lblTerzoThread, TerzaProgressBar, c2);
        c4 = new Corridore(lblQuartoThread, QuartaProgressBar, c3);
        
        t1 = new Thread(c1);
        t2 = new Thread(c2);
        t3 = new Thread(c3);
        t4 = new Thread(c4);
    }//GEN-LAST:event_RestartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GraficaStaffetta().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BottoneAvvia;
    private javax.swing.JButton Pausa;
    private javax.swing.JProgressBar PrimaProgressBar;
    private javax.swing.JProgressBar QuartaProgressBar;
    private javax.swing.JButton Restart;
    private javax.swing.JButton Riprendi;
    private javax.swing.JProgressBar SecondaProgressBar;
    private javax.swing.JProgressBar TerzaProgressBar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblPrimoThread;
    private javax.swing.JLabel lblQuartoThread;
    private javax.swing.JLabel lblSecondoThread;
    private javax.swing.JLabel lblTerzoThread;
    // End of variables declaration//GEN-END:variables
}
